import 'package:flutter_test/flutter_test.dart';
import 'package:sandwich_shop/models/saved_order.dart';

void main() {
  group('SavedOrder', () {
    test('creates SavedOrder with all required fields', () {
      final DateTime testDate = DateTime(2024, 11, 11, 14, 30);
      final SavedOrder order = SavedOrder(
        id: 1,
        orderId: 'ORD123456',
        totalAmount: 15.99,
        itemCount: 3,
        orderDate: testDate,
      );

      expect(order.id, equals(1));
      expect(order.orderId, equals('ORD123456'));
      expect(order.totalAmount, equals(15.99));
      expect(order.itemCount, equals(3));
      expect(order.orderDate, equals(testDate));
    });

    test('toMap converts SavedOrder to Map correctly', () {
      final DateTime testDate = DateTime(2024, 11, 11, 14, 30);
      final SavedOrder order = SavedOrder(
        id: 1,
        orderId: 'ORD123456',
        totalAmount: 15.99,
        itemCount: 3,
        orderDate: testDate,
      );

      final Map<String, Object?> map = order.toMap();

      expect(map['orderId'], equals('ORD123456'));
      expect(map['totalAmount'], equals(15.99));
      expect(map['itemCount'], equals(3));
      expect(map['orderDate'], equals(testDate.millisecondsSinceEpoch));
      // Note: id is not included in toMap as it's auto-generated by database
      expect(map.containsKey('id'), isFalse);
    });

    test('fromMap creates SavedOrder from Map correctly', () {
      final DateTime testDate = DateTime(2024, 11, 11, 14, 30);
      final Map<String, Object?> map = {
        'id': 1,
        'orderId': 'ORD123456',
        'totalAmount': 15.99,
        'itemCount': 3,
        'orderDate': testDate.millisecondsSinceEpoch,
      };

      final SavedOrder order = SavedOrder.fromMap(map);

      expect(order.id, equals(1));
      expect(order.orderId, equals('ORD123456'));
      expect(order.totalAmount, equals(15.99));
      expect(order.itemCount, equals(3));
      expect(order.orderDate.millisecondsSinceEpoch,
          equals(testDate.millisecondsSinceEpoch));
    });

    test('toMap and fromMap are inverse operations', () {
      final DateTime testDate = DateTime(2024, 11, 11, 14, 30);
      final SavedOrder originalOrder = SavedOrder(
        id: 42,
        orderId: 'ORD999888',
        totalAmount: 25.50,
        itemCount: 5,
        orderDate: testDate,
      );

      final Map<String, Object?> map = originalOrder.toMap();
      // Add id back to map for reconstruction
      map['id'] = originalOrder.id;
      final SavedOrder reconstructedOrder = SavedOrder.fromMap(map);

      expect(reconstructedOrder.id, equals(originalOrder.id));
      expect(reconstructedOrder.orderId, equals(originalOrder.orderId));
      expect(reconstructedOrder.totalAmount, equals(originalOrder.totalAmount));
      expect(reconstructedOrder.itemCount, equals(originalOrder.itemCount));
      expect(reconstructedOrder.orderDate.millisecondsSinceEpoch,
          equals(originalOrder.orderDate.millisecondsSinceEpoch));
    });

    test('handles zero values correctly', () {
      final DateTime testDate = DateTime(2024, 11, 11);
      final SavedOrder order = SavedOrder(
        id: 0,
        orderId: 'ORD000000',
        totalAmount: 0.0,
        itemCount: 0,
        orderDate: testDate,
      );

      expect(order.id, equals(0));
      expect(order.orderId, equals('ORD000000'));
      expect(order.totalAmount, equals(0.0));
      expect(order.itemCount, equals(0));
    });

    test('handles large values correctly', () {
      final DateTime testDate = DateTime(2024, 11, 11);
      final SavedOrder order = SavedOrder(
        id: 999999,
        orderId: 'ORD999999999999',
        totalAmount: 9999.99,
        itemCount: 100,
        orderDate: testDate,
      );

      expect(order.id, equals(999999));
      expect(order.orderId, equals('ORD999999999999'));
      expect(order.totalAmount, equals(9999.99));
      expect(order.itemCount, equals(100));
    });

    test('preserves decimal precision in totalAmount', () {
      final SavedOrder order = SavedOrder(
        id: 1,
        orderId: 'ORD123',
        totalAmount: 12.345,
        itemCount: 1,
        orderDate: DateTime.now(),
      );

      final Map<String, Object?> map = order.toMap();
      map['id'] = order.id;
      final SavedOrder reconstructed = SavedOrder.fromMap(map);

      expect(reconstructed.totalAmount, equals(12.345));
    });

    test('handles different date formats correctly', () {
      // Test with current time
      final DateTime now = DateTime.now();
      final SavedOrder order1 = SavedOrder(
        id: 1,
        orderId: 'ORD1',
        totalAmount: 10.0,
        itemCount: 1,
        orderDate: now,
      );

      final Map<String, Object?> map1 = order1.toMap();
      map1['id'] = 1;
      final SavedOrder reconstructed1 = SavedOrder.fromMap(map1);

      // Comparing milliseconds since epoch to avoid microsecond precision issues
      expect(reconstructed1.orderDate.millisecondsSinceEpoch,
          equals(now.millisecondsSinceEpoch));

      // Test with past date
      final DateTime past = DateTime(2020, 1, 1, 0, 0, 0);
      final SavedOrder order2 = SavedOrder(
        id: 2,
        orderId: 'ORD2',
        totalAmount: 20.0,
        itemCount: 2,
        orderDate: past,
      );

      final Map<String, Object?> map2 = order2.toMap();
      map2['id'] = 2;
      final SavedOrder reconstructed2 = SavedOrder.fromMap(map2);

      expect(reconstructed2.orderDate.millisecondsSinceEpoch,
          equals(past.millisecondsSinceEpoch));
    });
  });
}
